#!/bin/bash

GVS_DIR=GeoViS_M4D
BAR_DIR=$GVS_DIR/Viewer/AntTweakBar
TODAY=$(date +'%Y%m%d')

cd ..
zip -r geovis_$TODAY.zip \
$GVS_DIR/CMakeLists.txt \
$GVS_DIR/doxyfile \
$GVS_DIR/geovis.cpp \
$GVS_DIR/geovispar.cpp \
$GVS_DIR/GeoViSM4Dpar.pro \
$GVS_DIR/GeoViSM4D.pro \
$GVS_DIR/GeoViSM4D.pri \
$GVS_DIR/GvsGlobalDefs.h \
$GVS_DIR/README.md \
$GVS_DIR/README.css \
$GVS_DIR/Cam/Gvs2PICam.cpp \
$GVS_DIR/Cam/Gvs2PICam.h \
$GVS_DIR/Cam/Gvs4PICam.cpp \
$GVS_DIR/Cam/Gvs4PICam.h \
$GVS_DIR/Cam/GvsCamera.cpp \
$GVS_DIR/Cam/GvsCamera.h \
$GVS_DIR/Cam/GvsPanoramaCam.cpp \
$GVS_DIR/Cam/GvsPanoramaCam.h \
$GVS_DIR/Cam/GvsPinHoleCam.cpp \
$GVS_DIR/Cam/GvsPinHoleCam.h \
$GVS_DIR/Cam/GvsPinHoleStereoCam.cpp \
$GVS_DIR/Cam/GvsPinHoleStereoCam.h \
$GVS_DIR/Dev/GvsDevice.cpp \
$GVS_DIR/Dev/GvsDevice.h \
$GVS_DIR/Dev/GvsProjector.cpp \
$GVS_DIR/Dev/GvsProjector.h \
$GVS_DIR/Dev/GvsSampleMgr.cpp \
$GVS_DIR/Dev/GvsSampleMgr.h \
$GVS_DIR/Img/GvsChannelImg2D.cpp \
$GVS_DIR/Img/GvsChannelImg2D.h \
$GVS_DIR/Img/GvsColor.cpp \
$GVS_DIR/Img/GvsColor.h \
$GVS_DIR/Img/GvsIntersecOutput.cpp \
$GVS_DIR/Img/GvsIntersecOutput.h \
$GVS_DIR/Img/GvsPicIOEnvelope.cpp \
$GVS_DIR/Img/GvsPicIOEnvelope.h \
$GVS_DIR/Img/GvsPictureIO.cpp \
$GVS_DIR/Img/GvsPictureIO.h \
$GVS_DIR/Img/GvsPngIO.cpp \
$GVS_DIR/Img/GvsPngIO.h \
$GVS_DIR/Img/GvsPpmIO.cpp \
$GVS_DIR/Img/GvsPpmIO.h \
$GVS_DIR/Img/GvsTiffIO.cpp \
$GVS_DIR/Img/GvsTiffIO.h \
$GVS_DIR/Light/GvsFlashLight.cpp \
$GVS_DIR/Light/GvsFlashLight.h \
$GVS_DIR/Light/GvsLightSrc.cpp \
$GVS_DIR/Light/GvsLightSrc.h \
$GVS_DIR/Light/GvsLightSrcMgr.cpp \
$GVS_DIR/Light/GvsLightSrcMgr.h \
$GVS_DIR/Light/GvsPointLight.cpp \
$GVS_DIR/Light/GvsPointLight.h \
$GVS_DIR/MpiUtils/GvsMpiDefs.h \
$GVS_DIR/MpiUtils/MpiImage.cpp \
$GVS_DIR/MpiUtils/MpiImage.h \
$GVS_DIR/MpiUtils/MpiTaskManager.cpp \
$GVS_DIR/MpiUtils/MpiTaskManager.h \
$GVS_DIR/Obj/GvsBase.cpp \
$GVS_DIR/Obj/GvsBase.h \
$GVS_DIR/Obj/GvsBoundBox4D.cpp \
$GVS_DIR/Obj/GvsBoundBox4D.h \
$GVS_DIR/Obj/GvsBoundBox.cpp \
$GVS_DIR/Obj/GvsBoundBox.h \
$GVS_DIR/Obj/GvsOctree.cpp \
$GVS_DIR/Obj/GvsOctree.h \
$GVS_DIR/Obj/GvsObjPtrList.cpp \
$GVS_DIR/Obj/GvsObjPtrList.h \
$GVS_DIR/Obj/GvsSceneObj.cpp \
$GVS_DIR/Obj/GvsSceneObj.h \
$GVS_DIR/Obj/GvsSurface.cpp \
$GVS_DIR/Obj/GvsSurface.h \
$GVS_DIR/Obj/GvsTransformObj.cpp \
$GVS_DIR/Obj/GvsTransformObj.h \
$GVS_DIR/Obj/Comp/GvsCompoundObj.cpp \
$GVS_DIR/Obj/Comp/GvsCompoundObj.h \
$GVS_DIR/Obj/Comp/GvsLocalCompObj.cpp \
$GVS_DIR/Obj/Comp/GvsLocalCompObj.h \
$GVS_DIR/Obj/Comp/GvsCompoundOctreeObj.cpp \
$GVS_DIR/Obj/Comp/GvsCompoundOctreeObj.h \
$GVS_DIR/Obj/MeshObj/GvsOBJMesh.h \
$GVS_DIR/Obj/MeshObj/GvsOBJMesh.cpp \
$GVS_DIR/Obj/PlanarObj/GvsPlanarSurf.cpp \
$GVS_DIR/Obj/PlanarObj/GvsPlanarSurf.h \
$GVS_DIR/Obj/PlanarObj/GvsPlanarRing.h \
$GVS_DIR/Obj/PlanarObj/GvsPlanarRing.cpp \
$GVS_DIR/Obj/PlanarObj/GvsTriangle.cpp \
$GVS_DIR/Obj/PlanarObj/GvsTriangle.h \
$GVS_DIR/Obj/SolidObj/GvsSolBackground.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolBackground.h \
$GVS_DIR/Obj/SolidObj/GvsSolBox.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolBox.h \
$GVS_DIR/Obj/SolidObj/GvsSolConvexPrim.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolConvexPrim.h \
$GVS_DIR/Obj/SolidObj/GvsSolCylinder.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolCylinder.h \
$GVS_DIR/Obj/SolidObj/GvsSolEllipsoid.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolEllipsoid.h \
$GVS_DIR/Obj/SolidObj/GvsSolRing.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolRing.h \
$GVS_DIR/Obj/SolidObj/GvsSolidCSGObj.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolidCSGObj.h \
$GVS_DIR/Obj/SolidObj/GvsSolidDifferObj.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolidDifferObj.h \
$GVS_DIR/Obj/SolidObj/GvsSolidIntersecObj.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolidIntersecObj.h \
$GVS_DIR/Obj/SolidObj/GvsSolidObj.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolidObj.h \
$GVS_DIR/Obj/SolidObj/GvsSolidUnifiedObj.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolidUnifiedObj.h \
$GVS_DIR/Obj/SolidObj/GvsSolObjSpanList.cpp \
$GVS_DIR/Obj/SolidObj/GvsSolObjSpanList.h \
$GVS_DIR/Obj/STMotion/GvsLocalTetrad.cpp \
$GVS_DIR/Obj/STMotion/GvsLocalTetrad.h \
$GVS_DIR/Obj/STMotion/GvsStMotionConstVelocity.cpp \
$GVS_DIR/Obj/STMotion/GvsStMotionConstVelocity.h \
$GVS_DIR/Obj/STMotion/GvsStMotion.cpp \
$GVS_DIR/Obj/STMotion/GvsStMotionGeodesic.cpp \
$GVS_DIR/Obj/STMotion/GvsStMotionGeodesic.h \
$GVS_DIR/Obj/STMotion/GvsStMotion.h \
$GVS_DIR/Obj/STMotion/GvsStMotionWorldline.cpp \
$GVS_DIR/Obj/STMotion/GvsStMotionWorldline.h \
$GVS_DIR/Parser/* \
$GVS_DIR/Ray/GvsRayAllIS.cpp \
$GVS_DIR/Ray/GvsRayAllIS.h \
$GVS_DIR/Ray/GvsRayAnyIS.cpp \
$GVS_DIR/Ray/GvsRayAnyIS.h \
$GVS_DIR/Ray/GvsRayClosestIS.cpp \
$GVS_DIR/Ray/GvsRayClosestIS.h \
$GVS_DIR/Ray/GvsRay.cpp \
$GVS_DIR/Ray/GvsRayGen.cpp \
$GVS_DIR/Ray/GvsRayGen.h \
$GVS_DIR/Ray/GvsRay.h \
$GVS_DIR/Ray/GvsRayOneIS.cpp \
$GVS_DIR/Ray/GvsRayOneIS.h \
$GVS_DIR/Ray/GvsRayVisual.cpp \
$GVS_DIR/Ray/GvsRayVisual.h \
$GVS_DIR/Ray/GvsSurfIntersec.cpp \
$GVS_DIR/Ray/GvsSurfIntersec.h \
$GVS_DIR/Shader/GvsShader.cpp \
$GVS_DIR/Shader/GvsShader.h \
$GVS_DIR/Shader/Surface/GvsSurfaceShader.cpp \
$GVS_DIR/Shader/Surface/GvsSurfaceShader.h \
$GVS_DIR/Texture/GvsChequeredT2D.cpp \
$GVS_DIR/Texture/GvsChequeredT2D.h \
$GVS_DIR/Texture/GvsChequeredTimeT2D.cpp \
$GVS_DIR/Texture/GvsChequeredTimeT2D.h \
$GVS_DIR/Texture/GvsColorGradTex.cpp \
$GVS_DIR/Texture/GvsColorGradTex.h \
$GVS_DIR/Texture/GvsCheckerT2D.cpp \
$GVS_DIR/Texture/GvsCheckerT2D.h \
$GVS_DIR/Texture/GvsDieT2D.cpp \
$GVS_DIR/Texture/GvsDieT2D.h \
$GVS_DIR/Texture/GvsImg2DSampler.cpp \
$GVS_DIR/Texture/GvsImg2DSampler.h \
$GVS_DIR/Texture/GvsTexture2D.cpp \
$GVS_DIR/Texture/GvsTexture2D.h \
$GVS_DIR/Texture/GvsTexture.cpp \
$GVS_DIR/Texture/GvsTexture.h \
$GVS_DIR/Texture/GvsUniTex.cpp \
$GVS_DIR/Texture/GvsUniTex.h \
$GVS_DIR/Utils/GvsGeodSolver.cpp \
$GVS_DIR/Utils/GvsGeodSolver.h \
$GVS_DIR/Utils/GvsGramSchmidt.cpp \
$GVS_DIR/Utils/GvsGramSchmidt.h \
$GVS_DIR/Utils/GvsLog.cpp \
$GVS_DIR/Utils/GvsLog.h \
$GVS_DIR/examples/schwarzschild.scm \
$GVS_DIR/examples/sphereAroundBlackhole.scm \
$GVS_DIR/examples/whBox.scm \
$GVS_DIR/examples/morristhorne.scm \
$GVS_DIR/examples/minkRotSphere.scm \
$GVS_DIR/examples/minkWheel.scm \
$GVS_DIR/examples/fallEddFinkIn.scm \
$GVS_DIR/Viewer/CMakeLists.txt \
$GVS_DIR/Viewer/gl3w/gl3w.c \
$GVS_DIR/Viewer/gl3w/GL3/gl3.h \
$GVS_DIR/Viewer/gl3w/GL3/gl3w.h \
$GVS_DIR/Viewer/glm/*.hpp \
$GVS_DIR/Viewer/glm/core/* \
$GVS_DIR/Viewer/glm/gtc/* \
$GVS_DIR/Viewer/glm/gtx/* \
$GVS_DIR/Viewer/glm/virtrev/* \
$GVS_DIR/Viewer/GLShader.h \
$GVS_DIR/Viewer/GLShader.cpp \
$GVS_DIR/Viewer/main.cpp \
$GVS_DIR/Viewer/Utils.h \
$GVS_DIR/Viewer/Utils.cpp \
$GVS_DIR/Viewer/Shader/schwarzschildDisc.frag \
$GVS_DIR/Viewer/Shader/standard.frag \
$GVS_DIR/Viewer/Shader/standard.vert \
$GVS_DIR/Viewer/Shader/texCoords.frag \
$BAR_DIR/ChangeLog.txt \
$BAR_DIR/License.txt \
$BAR_DIR/Readme.txt \
$BAR_DIR/include/AntTweakBar.h \
$BAR_DIR/src/Makefile \
$BAR_DIR/src/Makefile.osx \
$BAR_DIR/src/Readme.txt \
$BAR_DIR/src/*.h \
$BAR_DIR/src/*.cpp \
$BAR_DIR/src/*.c \
$BAR_DIR/src/*.hlsl \
$BAR_DIR/src/res/*

cd -

